# Generated by Django 4.2.3 on 2023-08-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='event_title',
            field=models.CharField(default='Wedding Shoot', max_length=64),
            preserve_default=False,
        ),
    ]
